const Types={
    FETCH_USER:"FETCH_USER", 
    FETCH_QUESTIONS: "FETCH_QUESTIONS" ,
    FETCH_ALLUSERS: "FETCH_ALLUSERS" , 
    FetchQUESTIONWITHID:" FetchQUESTIONWITHID",
    FETCH_VOTE1:"FETCH_VOTE1",
    FETCH_VOTE2:"FETCH_VOTE2",
    FETCHQUESTIONVOTE:"FETCHQUESTIONVOTE",
    FETCHNEWQUESTION:"FETCHNEWQUESTION",
    FETCHANSWEREDQUESTIONS:'FETCHANSWEREDQUESTIONS',
    FETCHUNANSWEREDQUESTIONS:'FETCHUNANSWEREDQUESTIONS',
  }
  export default Types